"""msc_proj_v2 统一项目路径。"""

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"
ASSETS_DIR = PROJECT_ROOT / "assets"
CONFIGS_DIR = PROJECT_ROOT / "configs"

PUSHING_DATA_DIR = DATA_DIR / "pushing_data"
PUSHING_LEVEL1_SPLIT_CSV = PUSHING_DATA_DIR / "level1_dataset_split.csv"
PUSHING_AUGMENTATION_DIR = PUSHING_DATA_DIR / "augmentation"
PUSHING_YAW_RICH_V1_DIR = PUSHING_AUGMENTATION_DIR / "yaw_rich_v1"
PUSHING_BASELINE_PLUS_YAW_RICH_V1_DIR = (
    PUSHING_AUGMENTATION_DIR / "baseline_plus_yaw_rich_v1"
)
PUSHING_YAW_RICH_V1_SPLIT_CSV = PUSHING_YAW_RICH_V1_DIR / "level1_yaw_rich_split.csv"
PUSHING_AUGMENTED_LEVEL1_SPLIT_CSV = (
    PUSHING_BASELINE_PLUS_YAW_RICH_V1_DIR / "level1_forward_model_augmented_split.csv"
)
FORWARD_MODEL_RESULTS_DIR = RESULTS_DIR / "forward_model"
INVERSE_MODEL_RESULTS_DIR = RESULTS_DIR / "inverse_model"

INVERSE_MODEL_DATA_DIR = DATA_DIR / "inverse_model"
INVERSE_MODEL_MIDROW_DATA_DIR = INVERSE_MODEL_DATA_DIR / "midrow"
INVERSE_MODEL_MIDROW_TAU_0P03_DATA_DIR = INVERSE_MODEL_MIDROW_DATA_DIR / "tau_0p03"
INVERSE_REGION_DATASET_CSV = (
    INVERSE_MODEL_MIDROW_TAU_0P03_DATA_DIR / "inverse_region_dataset.csv"
)
INVERSE_ACTION_DATASET_DIR = (
    INVERSE_MODEL_MIDROW_TAU_0P03_DATA_DIR / "inverse_action_dataset"
)
INVERSE_ACTION_DATASET_MANIFEST_CSV = (
    INVERSE_MODEL_MIDROW_TAU_0P03_DATA_DIR / "inverse_action_dataset_manifest.csv"
)
INVERSE_REGION_LIBRARY_CSV = (
    INVERSE_MODEL_MIDROW_TAU_0P03_DATA_DIR / "inverse_region_library.csv"
)
INVERSE_ACTION_LIBRARY_CSV = (
    INVERSE_MODEL_MIDROW_TAU_0P03_DATA_DIR / "inverse_action_library.csv"
)

INVERSE_MODEL_MIDROW_RESULTS_DIR = INVERSE_MODEL_RESULTS_DIR
INVERSE_MODEL_MIDROW_MODELS_DIR = INVERSE_MODEL_RESULTS_DIR / "models" / "midrow"
INVERSE_REGION_MODEL_DIR = INVERSE_MODEL_MIDROW_MODELS_DIR / "region_tau_0p03"
INVERSE_ACTION_MODEL_DIR = (
    INVERSE_MODEL_MIDROW_MODELS_DIR / "action_tau_0p03_h256_256"
)
INVERSE_MODEL_MIDROW_EVALUATION_DIR = (
    INVERSE_MODEL_RESULTS_DIR / "evaluation" / "midrow"
)
INVERSE_MODEL_MIDROW_PROPOSALS_DIR = INVERSE_MODEL_RESULTS_DIR / "proposals" / "midrow"
INVERSE_DISCRETE_TWO_STAGE_PROPOSALS_DIR = (
    INVERSE_MODEL_MIDROW_PROPOSALS_DIR / "discrete_two_stage_tau_0p03_h256_256"
)
INVERSE_CONTINUOUS_WGMM_PROPOSALS_DIR = (
    INVERSE_MODEL_MIDROW_PROPOSALS_DIR
    / "continuous_wgmm_tau_0p03_h256_256_s3000"
)

HCR_DATA_DIR = DATA_DIR / "hcr"
HCR_RESULTS_DIR = RESULTS_DIR / "hcr"

HCR_V2_DATA_DIR = DATA_DIR / "hcr_v2"
HCR_V2_RESULTS_DIR = RESULTS_DIR / "hcr_v2"
